apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitwarden-secrets-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/ripplefcl/bws-cache
              tag: v3.2.2@sha256:84f4a96714b3f6690d3c091b4e0674c223e7989ed6a0dd344b42bbff7efe5302
            env:
              SECRET_TTL: 3600
              DEBUG: "true"
              ORG_ID:
                valueFrom:
                  secretKeyRef:
                    name: bws-secret
                    key: ORG_ID
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
              limits:
                memory: 100Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 5000
