apiVersion: v1
kind: Secret
metadata:
    name: bws-secret
stringData:
    ORG_ID: ENC[AES256_GCM,data:npsjbMpwUa6LB/yuoKaALaqvHhNztUeturMKhJtxc/5aJPQG,iv:ZWXNqKgiIOZ+EvFGtSYH7xNv7AML0EJFCgsgtlGSvTA=,tag:L3KQ/GVHkI8RzK8rpwRx1w==,type:str]
    token: ENC[AES256_GCM,data:Ef1Sd8kNhL6gMDDc8biAt+JcdTl5zmKU0abJ223j8XaiGHt+k/t6oleBvRTz9aAWcaM4/+z3qHQzgrr7pLoi890RcE60wcgk5CbZ6+0zyP0zDSV5fKkMSpmUvCRYgA==,iv:nhBU3YQ7hGJafYo+M98CAyEQ86nB58tTknRexh3ol40=,tag:Sh8Ky5/N1T62iSfWHCO2RA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sacnluj6uj66fya9qudxdtsn3xt0x04phchk3hs05kg573ksqqzqmxhfz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL0tKR09EVDllZjBuaE4y
            Q0MyWEFtNjZOV1lhd0FiTDBlTm13dWFBWUhJCjJ2UzhUd3RvQWRYR1hxSzNJUmVP
            dVY3L1ZWRzFsWkN0TXo0WUxMeEdVTjQKLS0tIDFKdnhyNExMZHpjVUVCUFQzd21t
            dXVMV3dadU1RYWJJaTFqMlJFTldweWsKynwU1VmhOImIXBqsHsaBDgdOhTYG8YIm
            FFHDbIfmPKp4FevfzlNfXwLx/q3Rkd2xNtUop0inISjpJPI65SXJpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-11T03:50:34Z"
    mac: ENC[AES256_GCM,data:dmrjUhC/jIJxAZGKxbyvXpk/3GD1V1w1xC08qjJgD/8wkiiigyDQqnh+D6jiSLDK1xFM//F334xoaaRT3iPLJfLXoY4cKm32WD0AwfwiY9D9GnUle9+5IWGzS4/C0aE6wmH0w6GvKPICcgb5Etmir8ssXwJDY7xmHDRwme5dbqk=,iv:1e1FkwwuDxdQoKhVU4f1DZrz5jmPaBlS0PmfFTlPcxo=,tag:zjTOt0K4o3xXT+/v3OLYHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
