---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: test
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: test-secret
  data:
  - secretKey: testdata
    remoteRef:
      key: TEST_KEY
