apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 15m
  chart:
    spec:
      chart: immich
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 15m

  values:

    postgresql:
      enabled: true
      image:
        registry: ghcr.io
        #repository: bo0tzz/cnpgvecto.rs
        repository: tensorchord/cloudnative-pgvecto.rs
        tag: 14.10-v0.1.13

    env:
      LOG_LEVEL: verbose

    redis:
      enabled: true

    immich:
      persistence:
        library:
          existingClaim: immich-nfs

    image:
      tag: "v1.100.0"

    server:
      resources:
        requests:
          cpu: 15m
          memory: 512M
      ingress:
        main:
          enabled: true
          ingressClassName: internal
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hosts:
            - host: &host "images.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host
              secretName: *host

    microservices:
      controller:
        replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 250M

    machine-learning:
      resources:
        requests:
          cpu: 100m
          memory: 2048M
      persistence:
        cache:
          size: 10Gi
          type: pvc
          accessMode: ReadWriteOnce
          storageClass: proxmox-data-csi
