apiVersion: v1
kind: Secret
metadata:
    name: database-immich-user
stringData:
    PASSWORD: ENC[AES256_GCM,data:088tggSTHtz8VQ57M5U=,iv:azuFOj5hSfc0rGNlR9oSdJ2t1KlSbdU0GYXO8qFrx9U=,tag:rEYAOh1fc/57BD3szG0QhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sacnluj6uj66fya9qudxdtsn3xt0x04phchk3hs05kg573ksqqzqmxhfz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UjluTkNnY01uUkxmQmhB
            dWIxb0N2OFJJM1Q3U3B4TUFhdFQvUmFxQ25rCmFUWDgwWnpRcDN0VjY5Zm91ZWZW
            V1hiWkh5NjZVRk52czRnQmpBRUJ5SW8KLS0tIFo5VnhzQmdZNTVnZGp6Nkl2djJO
            dFFTQ2ZmdmN3WTBmemo1QkhlYmorOFEKCn5E/GrBQityBP4AyTHIk3quzQxqe3fg
            hgkoJaliHgjqGcV6j2yXajZ5F2qG0ElcTPp/Xg56L4rPzXD83WX/kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T01:14:41Z"
    mac: ENC[AES256_GCM,data:IjdAyhOSbJOmIyZ0LSWRLGRcKgIz4P/VsGLTDY+3BaFGDjfEpCJMysMpH7ueBSBVOnZn7/2UpLEp8SbYqgF3zvA9P5SgdtDSfphHBhHeHpm6bZop0qUz+i5eChNcqwfZ1TO896cSqxa9Ku9cvDmJts6oSOG5FEX9V5ctXfwbo1o=,iv:9M0+wkkam/+bxYupxDIwuqWTVX6Dmzt1QjhjNze3jok=,tag:rHYyxVaVjpLtnu0H3HJNyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
