---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-config
  namespace: default
  labels:
    app.kubernetes.io/name: &name esphome
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
