---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name frigate
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        SECRET_DOMAIN: "{{ .SECRET_DOMAIN }}"
        FRIGATE_RTSP_PASSWORD: "{{ .FRIGATE_RTSP_PASSWORD }}"
        FRIGATE_DOORBELL_PASSWORD: "{{ .FRIGATE_DOORBELL_PASSWORD }}"
        FRIGATE_MQTT_USERNAME: "{{ .FRIGATE_MQTT_USERNAME }}"
        FRIGATE_MQTT_PASSWORD: "{{ .FRIGATE_MQTT_PASSWORD }}"
  dataFrom:
  - extract:
      key: frigate
