---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: mosquitto

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            passthrough: tpu_gpu
        containers:
          main:
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: 0.12.1
            env:
              TZ: America/New_York
              LIBVA_DRIVER_NAME: i965
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/version
                    port: &port 5000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 1000Mi
              limits:
                memory: 6000Mi
            securityContext:
              privileged: true

    service:
      main:
        ports:
          http:
            port: &port 5000
          rtsp:
            enabled: true
            port: 8554

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "frigate.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "frigate.${SECRET_DOMAIN}"
            secretName: frigate-tls

    securityContext:
      privileged: true

    persistence:
      data:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "172.16.0.11"
            path: /saspool1/frigate
      config-file:
        type: configMap
        name: frigate-configmap
        readOnly: true
        globalMounts: 
          - path:  /config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "172.16.0.11"
            path: /saspool1/frigate
        mountPath: /media
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/bus/usb
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 2Gi
        mountPath: /dev/shm
