---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: mosquitto

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            passthrough: tpu_gpu
            kubernetes.io/hostname: k3s-worker1
        containers:
          main:
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: 0.14.1
            env:
              TZ: America/New_York
              LIBVA_DRIVER_NAME: iHD
            envFrom:
              - secretRef:
                  name: frigate
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/version
                    port: &port 5000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 100m
                memory: 1000Mi
              limits:
                memory: 6000Mi

    service:
      main:
        controller: main
        ports:
          http:
            port: *port
          rtsp:
            port: &restream-port 8554
      external-rtsp:
        enabled: true
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          lbipam.cilium.io/ips: 172.16.0.217
        ports:
          rtsp-tcp:
            enabled: true
            port: *restream-port
            protocol: TCP
            targetPort: *restream-port

    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: "frigate.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http

    securityContext:
      privileged: true

    persistence:
      config:
        existingClaim: frigate-config
        globalMounts:
          - path: /data
      config-file:
        type: configMap
        name: frigate-configmap
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            #readOnly: true
      media:
        type: nfs
        server: 172.16.0.11
        path: /saspool1/frigate
        globalMounts:
          - path: /media/frigate
      cache:
        type: emptyDir
        medium: Memory
        sizeLimit: 4Gi
        globalMounts:
          - path: /dev/shm
      usb:
        type: hostPath
        hostPath: /dev/bus/usb
        hostPathType: Directory
        globalMounts:
          - path: /dev/bus/usb
