---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./config-pvc.yaml
  - ./externalsecret.yaml
configMapGenerator:
  - name: frigate-configmap
    files:
      - config.yml=./config/config.yml
generatorOptions:
  disableNameSuffixHash: true
