apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name jellyseerr-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        JELLYSEERR__API_KEY: "{{ .JELLYSEERR_API_KEY }}"
  dataFrom:
    - extract:
        key: jellyseerr
