ansible_become_pass: ENC[AES256_GCM,data:MnUpOJ8=,iv:teQe6tCj/CCHAnOo624z+mXDzfjJtRmVma8FhChKoGU=,tag:SmEpVseD9UzjvQzrD4vsyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sacnluj6uj66fya9qudxdtsn3xt0x04phchk3hs05kg573ksqqzqmxhfz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOFl1Z0premxZVk5Rdndv
            LzJxZlM5R3NjbW1VeEllRmFGdUM2Z3VLVmxvCmZCRFFaeFBCWHpqVGlOUzhQdUdm
            aFJKTmFrcXFKdVR5KzdVb2dwWWZIbTgKLS0tIHBpUnJkT21aaFYvd1A2T1JyUVll
            SFRYUTZlMXRlQ3NnOFlSRGVRQ3pRT1EKLoVzqv9DBRJHbeWzNWNxExWyTUR1HZGC
            7LLTnfPcIL7ar3TKPZM04cCQZ73RWG/gIdBAwq8gJXnp/ldUPEf9tQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-26T20:32:01Z"
    mac: ENC[AES256_GCM,data:qlj0h/GUXFOHF/IgtORZde23FVZr6bycenwigE4AM/mw+6djwFdPf5ZjEaNQQjNE+RbBx9UUQMAc/iLbXcvI2MWIqchY4/eVKmgJcWxWvnRSdUuo5l7jXOTSWm41tqgJE77A8wSz4GSczeF8JwgYMzSE3aqqyd4Ky7fVXdywMQM=,iv:m6ADhJWFw2oYkal1orCl6vMcsSRVOteee3q651vmASE=,tag:SIZIhcbp8h4NkAvX/FJIKQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
