ansible_become_pass: ENC[AES256_GCM,data:rAcUJWk=,iv:CjpyTXumxyftvBPze12CZrTwVvxuRtvDspZdbh28IcQ=,tag:S4AFBacYTPmYFCFt3Lh+eQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sacnluj6uj66fya9qudxdtsn3xt0x04phchk3hs05kg573ksqqzqmxhfz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N3VOUG5LdFJpV3ViWWRx
            eFl2NHFoK0FJM3NTYW9kQnRyUWh1NjFoY25FClpJZFdnTmpaa2xkcVFES1RYRVFT
            ZjIrbG5qY1hQUThveXhkeHpTTnJaTEEKLS0tIEVRalhCR1ZjaFdTei9Yd200Uk1P
            TDJWc1VaZHdWYzc2TC90UUZqb3prKzgKF7RgtmapMMZm0lIExU/hmww00PT0fzOo
            DFOpXgi5uPuwufzHX/R6EwjI0PuSpJEGaqfmmcm7HzYq6DfObrc5eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-26T05:56:28Z"
    mac: ENC[AES256_GCM,data:Qe+TUtUMxeKSD/DdWOlqRLnDbGBCteNwEA6IvO5A7uLwnvSVCZxjL4ajEUlHxUSaV6tcosKgtIuELrzvazoh/foQ+pUHEf96kKmjEcJAhgAiqQfNADLSvVXn1vtkQBJSEow6DtORVjAljnGzuAKZZE755/YoDUz/7F9DWFXoKg0=,iv:fcjwuO1gTzQxVjqFq1uB0KbcZFdttgIgVokhR/7oJFw=,tag:PjB11xca0GhWY1IY+VZ5AQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
