---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name sabnzbd-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        SABNZBD__API_KEY: "{{ .SABNZBD_API_KEY }}"
        SABNZBD__NZB_KEY: "{{ .SABNZBD_NZB_KEY }}"
  dataFrom:
  - extract:
      key: sabnzbd

