---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app zwave-js-ui
  namespace: flux-system
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
spec:
  path: ./kubernetes/apps/default/zwave-js-ui/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
