apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sacnluj6uj66fya9qudxdtsn3xt0x04phchk3hs05kg573ksqqzqmxhfz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTmNYNUgvRjVUOEtjOFMv
            a00rRzRQc3ZnbFFGQUY5Z2NsRkw4cnFwWUdRCnVncUVXdFpyZU5OMlBtR3ZJTDBU
            cE41ZTQrRnFZSk1JY0J3YUJRQkczNzgKLS0tIHVzNEpObGxyWlpLQjJqd0JzM1VJ
            bEgvU0ZRckJlcFQwN1g4VGpPWW1uYUEKxXFeXrulP4lqbuHvQkW5iOglFTl4dhqB
            L5zNMbBOk6U6bgN28MeVmLgpRrmY5luQ8C5V0mXhOC6n9cPMkLWxWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-26T06:58:28Z"
    mac: ENC[AES256_GCM,data:LE3G1Pn5KfLChZwuopujwXF2RSGdaTaBOyWAPgTW/0nWfNphdlrZgYSJsSDgYWYaC8QcV134CwC6INDR+SN6JdVBzWTPNdey+zsEbQdYLCdbY1sIwXnOWDZzItZJ+T/3eA9ucjMVPF8RaK1IaLFGJK/y5tnL7Tr9l5jai3Yhd9o=,iv:Z7X6zjl34pj7pXIhLLWmORQGfAMmVLF2nbEcZRbQTE8=,tag:adHHvjKKcDLXEMhI6piBlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
