---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: jellyfin/jellyfin
              tag: 10.10.2

            resources:
              requests:
                cpu: 100m
                #gpu.intel.com/i915: 1
                memory: 2000Mi
              limits:
                #gpu.intel.com/i915: 1
                memory: 2000Mi

    service:
      main:
        controller: main
        ports:
          http:
            port: 8096
          discovery:
            port: 7359
            protocol: UDP

    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /cache

      config:
        existingClaim: jellyfin-config
        advancedMounts:
          main:
            main:
              - path: /config

      media:
        type: nfs
        server: prox.${SECRET_DOMAIN}
        path: /saspool1/media
        globalMounts:
          - path: /mnt/media

