---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            kubernetes.io/hostname: k3s-worker2 # more cpu cores
          securityContext:
            runAsNonRoot: true
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: RuntimeDefault }
            supplementalGroups: [10000]
        containers:
          main:
            image:
              repository: jellyfin/jellyfin
              tag: 10.10.7
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 30

            resources:
              requests:
                cpu: 100m
                memory: 2Gi
              limits:
                memory: 4Gi

    service:
      main:
        controller: main
        ports:
          http:
            port: 8096
          discovery:
            port: 7359
            protocol: UDP

    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:

      tmpfs:
        type: emptyDir
        advancedMounts:
          main:
            - path: /cache
              subPath: cache
            - path: /config/log
              subPath: log
            - path: /tmp
              subPath: tmp

      config:
        existingClaim: jellyfin-config
        advancedMounts:
          main:
            main:
              - path: /config

      media:
        type: nfs
        server: prox.${SECRET_DOMAIN}
        path: /saspool1/media
        globalMounts:
          - path: /mnt/media

