---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: brody
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-csi
  resources:
    requests:
      storage: 10Gi
