---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name gitea-admin-user
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        email: "{{ .email }}"
  dataFrom:
  - extract:
      key: gitea

