---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gitea
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://dl.gitea.io/charts/
      chart: gitea
      version: 10.2.0
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system

  values:
    image:
      repository: gitea/gitea
      tag: 1.22.0
      pullPolicy: IfNotPresent

    service:
      http:
        port: 3000
    ingress:
      enabled: true
      className: internal
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "8000m"
        nginx.ingress.kubernetes.io/enable-global-auth: "false"
      hosts:
      - host: git.${SECRET_DOMAIN}
        paths:
          - path: /
            pathType: Prefix
      tls:
      - hosts:
        - git.${SECRET_DOMAIN}

    persistence:
      enabled: true
      create: false
      claimName: gitea-config

    gitea:
      admin:
        existingSecret: gitea

      config:
        security:
          PASSWORD_COMPLEXITY: spec
          #SECRET_KEY: set in secret
        database:
          DB_TYPE: sqlite3
        session:
          PROVIDER: memory
        cache:
          ADAPTER: memory
        queue:
          TYPE: level

    redis-cluser:
      enabled: false
    postgresql-ha:
      enabled: false
