---
# https://docs.cilium.io/en/latest/network/l2-announcements
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy
spec:
  loadBalancerIPs: true
  # NOTE: This might need to be set if you have more than one active NIC on your nodes
  # interfaces:
  #   - ^eno[0-9]+
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
spec:
  cidrs:
    - cidr: "172.16.0.210/32"
    - cidr: "172.16.0.211/32"
    - cidr: "172.16.0.212/32"
    - cidr: "172.16.0.213/32"
    - cidr: "172.16.0.214/32"
    - cidr: "172.16.0.215/32"
    - cidr: "172.16.0.216/32"
    - cidr: "172.16.0.217/32"
    - cidr: "172.16.0.218/32"
    - cidr: "172.16.0.219/32"
