---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-zwave-js-ui-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-csi
  resources:
    requests:
      storage: 1Gi
