---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./mosquitto/ks.yaml
  - ./frigate/ks.yaml
  - ./eufy-security-ws/ks.yaml
  - ./double-take/ks.yaml
