---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name sonarr-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        SONARR__API_KEY: "{{ .SONARR_API_KEY }}"
  dataFrom:
    - extract:
        key: sonarr
