---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name sonarr-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        SONARR__API_KEY: "{{ .SONARR_API_KEY }}"
  dataFrom:
    - extract:
        key: sonarr

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name sonarr-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: sonarr-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        SONARR__POSTGRES_HOST: '{{ index . "pgbouncer-host" }}'
        SONARR__POSTGRES_PORT: "5432"
        SONARR__POSTGRES_USER: '{{ .user }}'
        SONARR__POSTGRES_PASSWORD: '{{ .password }}'
        SONARR__POSTGRES_MAIN_DB: sonarr_main
        SONARR__POSTGRES_LOG_DB: sonarr_log
  dataFrom:
  - extract:
      key: postgres-pguser-sonarr
