---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app smokeping
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/smokeping
              tag: 2.8.2
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 15m
                memory: 128Mi
              limits:
                cpu: 50m
                memory: 192Mi
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: smokeping-config-v1
      data:
        enabled: true
        accessMode: ReadWriteOnce
