---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snmp-exporter-brocade
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: prometheus-snmp-exporter
      version: 7.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    fullnameOverride: *app
    extraArgs:
      - "--config.file=/config/snmp.yaml"
    extraConfigmapMounts:
      - name: *app
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: *app
        readOnly: true
        defaultMode: 420
    serviceMonitor:
      enabled: true
      namespace: monitoring
      params:
        - name: brocade
          module: ["brocade"]
          target: "brocade.${SECRET_DOMAIN}"
      path: /snmp
      scrapeTimeout: 10s
      relabelings:
        - { sourceLabels: ["__param_target"], targetLabel: instance }
