---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard
  - helmrelease.yaml
configMapGenerator:
  - name: snmp-exporter
    file:
      - snmp.yaml=./snmp.yaml
generatorOptions:
  disableNameSuffixHash: true
