---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: 2025.2.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      podAnnotations:
        secret.reloader.stakater.com/reload: authentik-secret
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: &secret authentik-secret
      env:
        AUTHENTIK_POSTGRES__HOST:
          valueFrom:
            secretKeyRef:
              name: authentik-secret-authentik-user
              key: HOST
        AUTHENTIK_POSTGRES__USER:
          valueFrom:
            secretKeyRef:
              name: authentik-secret-authentik-user
              key: LOGIN
        AUTHENTIK_POSTGRES__PASSWORD:
          valueFrom:
            secretKeyRef:
              name: authentik-secret-authentik-user
              key: PASSWORD
    authentik:
      redis:
        host: dragonfly.database.svc.cluster.local
    server:
      autoscaling:
        enabled: true
        minReplicas: 1
      resources:
        requests:
          cpu: 200m
        limits:
          memory: 1Gi
      metrics:
        prometheus:
          serviceMonitor:
            enabled: true
      ingress:
        main:
          enabled: true
          className: internal
          hosts:
            - host: "sso.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
    worker:
      autoscaling:
        enabled: true
        minReplicas: 1
      resources:
        requests:
          cpu: 200m
        limits:
          memory: 1Gi
