---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/default/paperless/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  prune: true
  components:
    - ../../../components/volsync
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  wait: false
  retryInterval: 2m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
