apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:JuiYK8tM+VfndDa2C20cO9l23YnX50y9tMHkbaMqmIB1SWUhREQB1g==,iv:Oa4xi8gjSiN1bzR7XjGmb6rk+244nUhjooijWHMyGgM=,tag:hEvg5XtMXoVRAOGuUaoz4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sacnluj6uj66fya9qudxdtsn3xt0x04phchk3hs05kg573ksqqzqmxhfz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3b1FxdlhGV1h3N2RtZWVJ
            NmFDVVlQMDJvQ2t3NlZ5MFVBTWZmbXMremlNCm9xS2YvRGhzQzJ0TFJuTVk0WUVi
            cXF2bmd3YkFwMW5CeVFxVXA0bWtMMDAKLS0tIFlESVZjNWdBN3VGRmZvaXgrVkNt
            bWRmcXBaNUtyWEd3Rm5lcDAra1F2Nm8Kb09s1o4xjFIAdETugEbXt/XxFRvgGApo
            jkEHaaCk6QMnDlnunEEqtzmJDdq7R3N8bGShkLPeRjHfzhNN5FnOvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-26T20:32:53Z"
    mac: ENC[AES256_GCM,data:ieFZNMtz8v9cpWibHcUQL2ofTAdtmHf4Z02GgS/mfUDIveHd0v4IldHL/dXgn8wu9zRC7iue8xna3maGaFRHSJjNFr1IqWMoG7w8x9sLZFLdjZDA2nPNGQPCCxQxQL8UYBHHvnjIqnTsdY5R4roQBnQU6mlJvKii941XkuDGrBw=,iv:KSnUicukjxZCgLc8kKK+zEyNuNdCxR0mXmh3X41hagA=,tag:7bCbtYvSESgljzHzfj1ADQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
