---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
data:
  # URLS
  IMMICH_WEB_URL: http://immich-web.media:3000
  IMMICH_SERVER_URL: http://immich-server.media:3001
  PUBLIC_IMMICH_SERVER_URL: https://images.${SECRET_DOMAIN}

  # REDIS
  REDIS_HOSTNAME: "immich-redis.media"
  REDIS_PORT: "6379"
