---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name immich-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  refreshInterval: 1m
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .JWT_SECRET }}"
        DB_USERNAME: "{{ .POSTGRES_SUPER_USER }}"
        DB_PASSWORD: "{{ .POSTGRES_SUPER_PASSWORD }}"
  data:
    - extract:
        key: immich
