---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name immich-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 2m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        DB_USERNAME: "{{ .POSTGRES_SUPER_USER }}"
        DB_PASSWORD: "{{ .POSTGRES_SUPER_PASSWORD }}"
  dataFrom:
  - extract:
      key: immich

