apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sacnluj6uj66fya9qudxdtsn3xt0x04phchk3hs05kg573ksqqzqmxhfz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVTlsMklyZkE2WXdsempF
            c2daaEM0OVpITTVvVGNWVkZNVFkybis3K1JFCmZ3WEpzMk1obkwxUGl0ZldxdTVs
            YTc0ZjhhRDR1SXpONytUM0VFMzc5cmcKLS0tIGxyeXIycXhaelBEMkd5WnhFT1po
            T1JiQ1YyOFRaQVpMQWp4UlE2VVdETWMKKH9MJb6B1A3ZNnzS2KyWwdCkaNCZO+oC
            ujfnmx6lNrX4N/W8sJ5KWOZP0yoRYGg0eRV+Ei2298XEpy/2Cxr7lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-26T01:26:02Z"
    mac: ENC[AES256_GCM,data:1ICi12Ar3Mm131WnvVmiimbY6d5HWL57rmMsJ+YryUtB0mcZQJLLZ64LofPsa32Oui1v6q7ovdd2XbZcb9/tHFxVnQYSD03HityfyRKAXf02QFkGd0iv0E2zQ4Gj8IKTqjlWFKx4YlMaf+Y/e2tNsC8wR01QmdXYyjKgG5ZoyIY=,iv:IZki826v6lpJMS06q5QboHqIFwYf4N0y3eJ2oLxdGt8=,tag:DhLsSMr2JZzF7oe+UM0XYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
