---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name external-dns-opnsense
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        OPNSENSE_API_KEY: "{{ .api_key }}"
        OPNSENSE_API_SECRET: "{{ .api_secret }}"
  dataFrom:
  - extract:
      key: external-dns-opnsense
