---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name external-dns-opnsense
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        api_key: "{{ .api_key }}"
        api_secret: "{{ .api_secret }}"
  dataFrom:
  - extract:
      key: external-dns-opnsense
