---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app capacitor
  namespace: flux-system
spec:
  path: ./kubernetes/apps/flux-system/capacitor/
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  targetNamespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
