---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name radarr-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        RADARR__API_KEY: "{{ .RADARR_API_KEY }}"
  dataFrom:
    - extract:
        key: radarr
