---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name radarr-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        RADARR__API_KEY: "{{ .RADARR_API_KEY }}"
  dataFrom:
    - extract:
        key: radarr

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name radarr-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: radarr-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        RADARR__POSTGRES_HOST: '{{ index . "pgbouncer-host" }}'
        RADARR__POSTGRES_PORT: "5432"
        RADARR__POSTGRES_USER: '{{ .user }}'
        RADARR__POSTGRES_PASSWORD: '{{ .password }}'
        RADARR__POSTGRES_MAIN_DB: radarr_main
        RADARR__POSTGRES_LOG_DB: radarr_log
  dataFrom:
  - extract:
      key: postgres-pguser-radarr
