---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-bind
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: registry.k8s.io/external-dns/external-dns
              tag: v0.15.0@sha256:338dd8c526e1337a12db0c8ee81a59ce5815ea51b73756affcd1e5dca530105c
            env:
              EXTERNAL_DNS_RFC2136_HOST: "10.5.0.3"
              EXTERNAL_DNS_RFC2136_PORT: "53"
              EXTERNAL_DNS_RFC2136_ZONE: ${SECRET_DOMAIN}
              EXTERNAL_DNS_RFC2136_TSIG_AXFR: "true"
              EXTERNAL_DNS_RFC2136_TSIG_KEYNAME: externaldns
              EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG: hmac-sha256
            envFrom:
              - secretRef:
                  name: external-dns-bind-secret
            args:
              - --domain-filter=${SECRET_DOMAIN}
              - --interval=1m
              - --log-format=text
              - --log-level=debug
              - --metrics-address=:7979
              - --policy=sync
              - --provider=rfc2136
              - --registry=txt
              - --source=ingress
              - --source=service
              - --txt-owner-id=default
              - --txt-prefix=k8s.
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 7979
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
    serviceAccount:
      create: true
      name: *app
    service:
      main:
        ports:
          http:
            port: *port
    serviceMonitor:
      main:
        enabled: true
