apiVersion: v1
kind: Secret
metadata:
    name: external-dns-bind-secret
stringData:
    EXTERNAL_DNS_RFC2136_HOST: ENC[AES256_GCM,data:QAXsCPLHnsY=,iv:Y/rcY8fNDeH1k32dME/sfrNJfY1HpLjdMz60JiXMsCo=,tag:L+wofz5vVly1UAXAvoyQHA==,type:str]
    EXTERNAL_DNS_RFC2136_TSIG_SECRET: ENC[AES256_GCM,data:Io0vLez08Fu01AySWVph+XeOblBjpSex8dBBjFDSWqGTXzsPcstpYLe6XWE=,iv:qT57u1XsVi3yNYePjZ5NKCl+koe9JyO7PZ//KMvEnQI=,tag:WnvBEcfG/zl2LbjmBTPPpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sacnluj6uj66fya9qudxdtsn3xt0x04phchk3hs05kg573ksqqzqmxhfz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M1ZqU1VsUk1GTVBaaWxq
            UXIzSlNTemNWUkp5ZWtQUW1POVJ3dXMxUVhvCmFuZ0FGL09EbWFCUmRleG50QzRv
            bHc5MDZPeUw5ZXEvek5vUUVqZXdOUzgKLS0tIG1YRzBOTjFjWEhpbGVrOGNhd1gy
            bEVBbjRNelRkUWpFYkd2OEpnSGF3cHMKEEu8uQ6NZ7cRzOfDWwT05znXRFQzcRq/
            ruSMG2jvf7bbsuk9OyE93KUpt7PzHo8nXoad+BkAMIie/EVoHEZB6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-17T22:13:18Z"
    mac: ENC[AES256_GCM,data:SpOtNg1QFVCpQNLjEiPxN8XmQpKB4Qq8Ywa3y4cGAu9stZgPDxggDusXTnWiOdMUtcoi1V2vk37V2bgmctL9Zf9ImPxpdjRLAgNYZquhKAGJJjAVQ/VRIb2Uc6FyaVFi5AEf+WUbhifGzdlYlQa8Gv6fUJSLfwQc3ffbz3aHVVY=,iv:KTr9Pfgq8KMFjcB7DLxgrX21kJgMyX+hQ1Pl01U/A1A=,tag:4x/Zk1W+nlMrJitzmNv6gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
