---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snmp-exporter-brocade
  namespace: flux-system
spec:
  targetNamespace: monitoring
  path: ./kubernetes/apps/monitoring/snmp-exporter/brocade
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  wait: false
