apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:VjSzaNqYUlvxpLGzf51uC71zjw==,iv:hypnDsjGWgqKJge9QUpetOY6Wc1rpitgZtiRgj/VWNY=,tag:0rwiE6GKK8EuQJAL3BzATg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
    SECRET_DOMAIN: ENC[AES256_GCM,data:bdZ8t9R3yw==,iv:VqpWdqIW84BGjL0XzY4/0iADtsmeDf5egMrc7GtRQmY=,tag:szgKJqujmhMa/E8noKAwLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sacnluj6uj66fya9qudxdtsn3xt0x04phchk3hs05kg573ksqqzqmxhfz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdzEvbXpWY28rMEhEYkV6
            TUVFT2ZKbWpzQm1UcWVhQ2tnUFFZb2tOU1JjClhZa2N5ZnNQMGt6aHUzdU5OLzZF
            b1JIZGZtdzZiMnl6Z3B2R1ZCTzVYVTgKLS0tIGtoYlYxVDBValpOOEtKOGZCZ0JI
            MEdnWG5ZUEYzVndOczZhTDZZL1ZxNDgKhxPmaQBotm2qoap6jSLKz71rmjj9yqmr
            bXvbr+b2i/TQgquY28ngM08dzdDbrsTlaZ7zD4qWz2kJ/lVkGSEjeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-26T05:57:11Z"
    mac: ENC[AES256_GCM,data:CUX68Wa9fLXAx6LVEPOqhslI1BTZS5gYkTuP1xXluXvOFh9jUi2ctR7v4DpUZpIx6jTmVWZxj+3H2fQsxYTYC+1vRxa63uQByLJW3ELg5EheL8dF6SACbMtUYO2WaNahS28Gz6MF0RJv0BD18+bk2Kf6+DDr7xtt4hL9ErAMJS0=,iv:h2ZUuMJsCh04VUBSk3C8te/B9tvr5nyxhSIipssDnKg=,tag:jIy2BZukNMb/s3Ykg0GzrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
