---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app karakeep
  namespace: flux-system
spec:
  targetNamespace: default
  path: ./kubernetes/apps/default/karakeep/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  prune: true
  components:
    - ../../../../components/volsync
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  wait: false
  retryInterval: 2m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
