---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name pgadmin-secrets
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        PGADMIN_DEFAULT_EMAIL: "{{ .username }}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: pgadmin
