---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  volumeName: omada-data-pv
