---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  volumeName: omada-data-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: omada-data-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
