---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name postgres-superuser
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        username: |-
          {{ .postgres_user }}
        password: |-
          {{ .postgres_pw }}
  dataFrom:
    - extract:
        key: *name

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name minio-pgsql
spec:
  secretstoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: *name
      data:
        minio_s3_access_key: |-
          {{ .minio_user }}
        minio_s3_secret_access_key: |-
          {{ .minio_secret }}
  dataFrom:
    - extract:
        key: *name
