---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app paperless
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 30m
  target:
    name: &app-secret
    template:
      data:
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_DBUSER: "{{ .PAPERLESS_DBUSER }}"
        PAPERLESS_DBPASS: "{{ .PAPERLESS_DBPASS }}"
  dataFrom:
  - extract:
      key: paperless
