apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: 65to1
data:
  default.conf: |-
    server {
            listen 80 default_server;
            root /var/www/html/65to1;
            server_name  _;
            index index.php;
            location / {
                try_files $uri $uri/ /index.php?$args;
            }
            location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass www65to1-site:9000;
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param   PATH_INFO       $fastcgi_path_info;
            }
        }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpconfig
  namespace: 65to1
data:
  custom.ini: short_open_tag = On
