---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./mariadb-helmrelease.yaml
  - ./mariadb-pvc.yaml
  - ./mariadb-secret.sops.yaml
  - ./pvc.yaml
  - ./configmap.yaml
  - ./ingress.yaml
  - ./service.yaml
  - ./deployment.yaml
