---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 65to1-nfs
  namespace: 65to1
spec:
  storageClassName: 65to1-nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /saspool1/65to1
    server: prox.jw2.org
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 65to1-nfs
  namespace: 65to1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: 65to1-nfs
  resources:
    requests:
      storage: 5Gi
