---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app envoy-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
  interval: 1h
  values:
    config:
      envoyGateway:
        provider:
          type: Kubernetes
          kubernetes:
            deploy:
              type: GatewayNamespace
    global:
      images:
        envoyGateway:
          image: mirror.gcr.io/envoyproxy/gateway-dev:latest@sha256:4c8eb079726d89bad3e5eda8c34162d66a3cdc6890f46f7235a2f2f4eda801a9
