---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name ext-postgres-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  refreshInterval: 1m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: "{{ .postgres_user }}"
        POSTGRES_PASS: "{{ .postgres_pw }}"
  data:
    - extract:
        key: postgres-superuser
